### ISSUE TITLE
Impossible to build.

### ISSUE THREAD

**Issue by Smellon69** [LilPidgey/EagleVM#3]
I can build the .dll and the other .exe without any issues, but I encounter numerous errors when trying to build the main .exe. Are you using v143 build tools on C++20 preview with multibyte? I'm struggling to identify what I might be doing wrong. Unfortunately, it's quite late now, and I'm unable to send images of the errors, but I'll do so tomorrow.

**Comment by Smellon69** [comment]
Also a quick question, how does this compare against [https://github.com/weak1337/Alcatraz/tree/master/Alcatraz](Alcatraz), a x64 PE Obfuscator on Github.

**Comment by LilPidgey** [comment]
I'm unable to help you without the list of build errors. Its possible you did not clone the submodules correctly so make sure you have done that.

I am not familiar with Alcatraz but the project seems like a finished product with several code obfuscation features. Meanwhile, EagleVM is an active work in progress project with a primary focus of obfuscation through code virtualization. I plan to implement other obfuscation techniques in the future.

**Comment by Smellon69** [comment]
> I'm unable to help you without the list of build errors. Its possible you did not clone the submodules correctly so make sure you have done that.
> 
> 
> 
> I am not familiar with Alcatraz but the project seems like a finished product with several code obfuscation features. Meanwhile, EagleVM is an active work in progress project with a primary focus of obfuscation through code virtualization. I plan to implement other obfuscation techniques in the future.

What I'm asking is, does the virtualization basically substitute obfuscation to an extent

**Comment by LilPidgey** [comment]
Code virtualization is obfuscation. I do not recommend that it is the sole method used to obfuscate your program. For instance, commercial code obfuscation tools like Themida and VMProtect layer obfuscation methods (like Alcatraz) to make their virtual machines more difficult to reverse engineer.

**Comment by Smellon69** [comment]
![image](https://github.com/LilPidgey/EagleVM/assets/74884194/da2dbd89-d683-401c-94da-6d82c8e588b2)
_, _1, _2 don't even exist

**Comment by LilPidgey** [comment]
Please share actual errors generated by the compiler rather than screenshots of the code.

The tuple is no longer deconstructed with a _0 rather is uses _. The code should look like this:
```
    for (auto& [_, _1, _2, encoded_bytes] : handler_bytes)
        vm_section_bytes += encoded_bytes;
```
If this modification was not made by you please clone the repo again and try to compile it.

**Comment by Smellon69** [comment]
> Please share actual errors generated by the compiler rather than screenshots of the code.
> 
> 
> 
> The tuple is no longer deconstructed with a _0 rather is uses _. The code should look like this:
> 
> ```
> 
>     for (auto& [_, _1, _2, encoded_bytes] : handler_bytes)
> 
>         vm_section_bytes += encoded_bytes;
> 
> ```
> 
> If this modification was not made by you please clone the repo again or pull forward and try to compile it.

I was messing around with it. It was originally _ and still giving the error

**Comment by Smellon69** [comment]
ok so I had like 15 include errors I didn't notice. I fixed them all and the error went away lol

**Comment by Smellon69** [comment]
ahh yes 
C:\Users\Smellon\Desktop\vcpkg\vcpkg\installed\x64-windows\include\Zydis\Generated\EnumRegister.h(5,1): error C2011: 'ZydisRegister_': 'enum' type redefinition

**Comment by LilPidgey** [comment]
This project does not use vcpkg. Please make sure that you have the submodules for this project cloned, they are included in the project automatically. Disable it in the project settings or uninstall the vcpkg dependency.

Have you made any changes to the project? If so, please clarify if the project even compiles without any of your changes. Or are you trying to compile the source from the repo?
